In [1]:
import pandas as pd
import numpy as np

In [119]:
mcf= pd.read_csv("data/mcf_clean_data.csv")
len(mcf)

22719

In [120]:
mcf.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
1,705309ff2a8d68b7ee215b6e2fc420ab,Manager (Facilities Management),Manager (Facilities Management),<p><strong >Role Overview</strong></p><p>We ar...,Role Overview We are seeking a Facilities Mana...,8,"[""Fire Safety"", ""Management Skills"", ""Sustaina...","[""Real Estate / Property Management""]","[""Permanent""]","[""Manager""]"
2,4a68226fc8b1d6f39bcf78451f7bc198,Sales Administrator,Sales Administrator,<ul>\n <li>Serve as administrator / key opera...,Serve as administrator / key operator for all ...,1,"[""Sales"", ""Microsoft Office"", ""Microsoft Excel...","[""Hospitality"", ""Sales / Retail""]","[""Full Time""]","[""Executive""]"
3,4726f24811127db6967fd1c07ec7ae77,Assistant Field Engineer(Construction),Assistant Field Engineer(Construction),<h3><strong>Our Company:</strong></h3>\n<p>Our...,Our Company: Our company develops ICT(Informat...,1,"[""Troubleshooting"", ""Construction"", ""Hardware""...","[""Customer Service"", ""Engineering"", ""Professio...","[""Full Time""]","[""Fresh/entry level""]"
4,301389565abb7d8ddd32efebb58776cf,Electronic Keyboard Teacher,Electronic Keyboard Teacher,<ul>\n <li>Teaching lessons to students at al...,Teaching lessons to students at all skill leve...,1,"[""Piano"", ""Classical"", ""Microsoft Excel"", ""Tea...","[""Education and Training""]","[""Full Time""]","[""Non-executive""]"

In [121]:
mcf.dtypes

uuid                      object
raw_title                 object
title                     object
raw_description           object
description               object
minimumYearsExperience     int64
skills                    object
categories                object
employmentTypes           object
positionLevels            object
dtype: object

In [122]:
mcf["positionLevels"].unique()

array(['["Junior Executive"]', '["Manager"]', '["Executive"]',
       '["Fresh/entry level"]', '["Non-executive"]', '["Professional"]',
       '["Senior Executive"]', '["Senior Management"]',
       '["Middle Management"]', '["Manager", "Executive"]',
       '["Middle Management", "Manager"]',
       '["Non-executive", "Fresh/entry level"]',
       '["Executive", "Fresh/entry level"]',
       '["Senior Management", "Manager"]'], dtype=object)

### Filter entry level and jobs with bachelor's degree

In [123]:
keywords = r"bachelor|degree|graduate|university|undergraduate|tertiary"
levels = r'"Fresh/entry level"|"Junior Executive"'

mcf_filtered1 = mcf[
    (
        (mcf["minimumYearsExperience"] == 0) |
        (mcf["positionLevels"].str.contains(levels, case=False, na=False))
    )
    &
    (mcf["description"].str.contains(keywords, case=False, na=False))
     & 
    (mcf["minimumYearsExperience"]<4)
   
]

mcf_filtered1.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
11,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]"
50,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]"
57,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]"
70,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]"

In [124]:
len(mcf_filtered1)

1589

In [125]:
mcf_filtered1["minimumYearsExperience"].value_counts()

minimumYearsExperience
0    732
1    459
2    275
3    123
Name: count, dtype: int64

In [126]:
mcf_filtered1["positionLevels"].unique()

array(['["Junior Executive"]', '["Fresh/entry level"]',
       '["Professional"]', '["Non-executive"]', '["Senior Executive"]',
       '["Executive"]', '["Manager"]',
       '["Non-executive", "Fresh/entry level"]'], dtype=object)

### Save dataset

In [127]:
mcf_filtered1.to_csv("data/mcf_entrylevel.csv", index=False)

# After extracting skills from skills future into csv, do a check

In [2]:
mcf_skills= pd.read_csv("data/mcf_entrylevel.csv")
len(mcf_skills)

1589

In [5]:
mcf_skills.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

In [6]:
mcf_skills.tail()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
1584,5997b3eeac3edbf61b881117e3086a98,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Lead Generation"",...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Delivery | Customer Management | Coachin...,NaN,error: Section 'extracted_apps_and_tools' not ...
1585,49a9476ace8427dd51d829be014e3b9b,Sales Executive (Manufacturing / Construction ...,Sales Executive (Manufacturing / Construction ...,<ul><li><strong>Well Established Company</stro...,Well Established Company Basic $ 3500 - $ 4500...,1,"[""Product Knowledge"", ""Negotiation"", ""Market R...","[""Building and Construction"", ""Others""]","[""Permanent"", ""Full Time""]","[""Junior Executive""]",Technical Sales Support | Sales Management | S...,AutoCAD,success
1586,c66aaa3d3934826a0ad6d163a3eeb79b,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Customer Management | Performance Management |...,NaN,error: Section 'extracted_apps_and_tools' not ...
1587,f7fcb794db5767a1eb03d5435572f7f2,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Sales"", ""Leadersh...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Strategy | Customer Management | Sales D...,NaN,error: Section 'extracted_apps_and_tools' not ...
1588,ecea94ed9e208e4b4447550256713733,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Management | Onboarding | Total Rewards ...,NaN,error: Section 'extracted_apps_and_tools' not ...

check whether any columns  have both empty extracted skills and extracted_apps_tools

In [10]:
mask = (
    mcf_skills["extracted_skills"].fillna("").astype(str).str.strip().eq("")
    & mcf_skills["extracted_apps_tools"].fillna("").astype(str).str.strip().eq("")
)

print("Any rows with both empty?", mask.any())
print("Number of such rows:", mask.sum())

mcf_skills.loc[mask, ].head()

Any rows with both empty? True
Number of such rows: 7

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
111,07875a80d2aaf783c2dceba1cf7091f2,Event Activation Representative (Entry Level),Event Activation Representative (Entry Level),<p>🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? ...,🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? NO ...,0,"[""Lead Generation"", ""Excellent Communication S...","[""Marketing / Public Relations""]","[""Temporary"", ""Full Time""]","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...
491,28a10008ca736207c901456a0beb9688,HR Recruitment Executive ( Entry Level ) #HCT,HR Recruitment Executive ( Entry Level ) #HCT,<p><em>We pride ourselves to provide quality s...,We pride ourselves to provide quality services...,0,"[""Advertising"", ""Social Media"", ""Telephone Man...","[""Healthcare / Pharmaceutical""]","[""Contract"", ""Part Time"", ""Permanent"", ""Full T...","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...
555,a4f79610a004066a25590f5a0c6e52ee,Research Fellow (Nanomaterials & Quantum Dot O...,Research Fellow (Nanomaterials & Quantum Dot O...,<p>CINTRA is a French-Singaporean joint resear...,CINTRA is a French-Singaporean joint research ...,0,"[""Higher Education"", ""Materials Science"", ""Sci...","[""Sciences / Laboratory / R&D""]","[""Contract"", ""Full Time""]","[""Professional""]",NaN,NaN,error: Skills download failed.
645,110900226420b0d243eae09cbc53e189,[2026 Intake] Assurance (Financial Services) A...,[2026 Intake] Assurance (Financial Services) A...,"<p>At Baker Tilly Singapore, we welcome highly...","At Baker Tilly Singapore, we welcome highly mo...",0,"[""Due Diligence"", ""Assurance"", ""Risk Managemen...","[""Accounting / Auditing / Taxation""]","[""Full Time""]","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...
675,dbdb950df1b46076ad8245838eb8152e,Software Quality & Manual Testing (UAT / SIT) ...,Software Quality & Manual Testing (UAT / SIT) ...,<p>Recruiter Comments:</p>\r\n<p>- Poly grads ...,"Recruiter Comments: - Poly grads are welcomed,...",1,"[""Wealth Management"", ""UAT"", ""Confluence"", ""fu...","[""Banking and Finance"", ""Information Technolog...","[""Contract"", ""Full Time""]","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...

Check on skills future website if actually no skills extracted

In [12]:
for idx, desc in mcf_skills.loc[mask, "description"].items():
    print(f"\nIndex {idx}:\n{desc}\n")
    print("-" * 80)

Index 111:
🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? NO WORRIES! Join the frontlines of exciting events! 🚀 What’s In It For You • 🎉 Live Campaign Activations – Bring events to life for top brands. • 🤝 Client-Facing Experience – Build relationships face-to-face. • 🕴 Sharpen Presentation Skills – Learn from experienced mentors. Why You’ll Love It Here: • ✨ Training provided, no background needed. • 👯‍♀ Work with a fun, motivated team. • 🎊 Active, engaging role – never boring. 💸 Weekly Pay + Commission Bonuses! Plus: • 📈 Level-up training and growth plans. • 🧠 Opportunities to lead future activations. • ✈ Travel perks for standout performers.

--------------------------------------------------------------------------------

Index 491:
We pride ourselves to provide quality services as a leading recruitment consultancy in Singapore. We are looking for dynamic, driven and focus individual to join our distinctive team in driving the business development strategy and recruitment processes for our clients. If you think you can take up the challenge as a professional Recruitment Consultant in this ‘people oriented’ field, do not hesitate, come and join us! Responsibilities: • Identify and assess potential candidates • Conduct interview and manage selection procedures • Design job descriptions and interview questions • Organize and attend recruitment events • Lead discussions in quarterly and annual hiring needs by department • Foster long-term relationships with past applicants and potential candidates • Involve actively in Human Resource activities with regards to Hiring and Managing of potential candidates Requirements: • Degree in any Discipline • Candidates with strong track record in sports or co-curricular activities will have an added advantage • Candidate with great team spirit, persistency, good communication and interpersonal skills are welcome to apply Interested candidates please send in your resume to: clinicalresearch@recruitexpress.com.sg EA Personnel: Valerie Yong Kian Fung CEI No.: R1103704 Recruit Express Pte Ltd, EA License No.: 99C4599

--------------------------------------------------------------------------------

Index 555:
CINTRA is a French-Singaporean joint research laboratory, a CNRS International Research Laboratory under the French Ministry of Higher Education and Research. It is a collaboration between the French National Centre for Scientific Research (CNRS), Nanyang Technological University (NTU) and Thales, bringing together researchers and students from France and Singapore. The research focus of this joint laboratory is towards the development of innovative nanotechnologies and nanomaterials for various electronic and photonic applications. We are looking for a Research Fellow that will lead advanced research on halide perovskite quantum dots (PQDs) for optoelectronic and display applications. The role focuses on the design, synthesis, stabilization, and integration of PQDs into polymer-based color conversion layers. The successful candidate will develop robust PQD/polymer composite films, optimize scalable film fabrication processes, and perform comprehensive optical and structural characterization. Key Responsibilities: Investigating degradation mechanisms, improving material stability and performance, and collaborating with interdisciplinary research teams. Contribute to high-impact publications, mentor junior researchers, and support laboratory operations and safety. Job Requirements: PhD in Chemistry, Materials Science, or a closely related field. Demonstrated expertise in perovskite quantum dot synthesis and stabilization strategies. Strong experience with optical and structural characterization techniques. Proven ability to fabricate and optimize polymer-based nanocomposite films. Effective problem-solving skills. ​ We regret that only shortlisted candidates will be notified.

--------------------------------------------------------------------------------

Index 645:
At Baker Tilly Singapore, we welcome highly motivated and committed individuals who share our core values to join us. We are committed to our values of leading by example, delivering quality services with integrity, communicating openly, acting ethically, and fostering a community built around civic responsibility and teamwork. We are looking for an Assurance (Financial Services) Associate, who will be involved in various sizes of financial services audit engagements which include planning, performing, and concluding the engagement. The Assurance Associate will be exposed to a broad range of capital markets entities and investment funds such as private equities, real estate, mutual funds, variable capital companies, etc. In this role, you will: • Involvement in a broad range of statutory and regulatory audit assignments for our financial services clients • Assist in obtaining all necessary audit working papers and documentation including researching and documenting facts and findings • Identify and communicate accounting and auditing matters to managers and partners • Identify performance improvement opportunities • Interact with clients to help ensure that the information flow from the client to the audit team is efficient We are looking for people with the following: • Graduates with an Accountancy degree or equivalent professional qualification in Accountancy • Accountancy undergraduates in the final year of study are welcome to apply • Good command of the English language • Strong interpersonal and client relationship skills

--------------------------------------------------------------------------------

Index 675:
Recruiter Comments: - Poly grads are welcomed, can be fresh graduates, good working attitude, logical and analytical thinking - Writing of test cases (can be trained) - Good to have Jira, SQL not required Job Description Your role will require close collaboration across multiple areas within the organization including but not limited to: 1. Project Management Office (PMO) 2. Information Technology (IT) 3. Product Development & Strategy (PD&S) 4. Business Units / Divisions (BU/Ds) 5. Operations (Ops) 6. Risk Management 8. Other relevant units as needed You will need to develop expertise in understanding the business processes and functions supported by the new system as well as conduct detailed reviews of user requirements and specifications. You will also need to develop and execute test plans, procedures and scenarios to ensure that the system meets all requirements and works seamlessly with other systems. Responsibilities: • Define, develop, document, execute and report on test approaches and plans. • Collaborate closely with project teams as well as other relevant stakeholders such as end users, subject matter experts, technical teams etc. • Develop and maintain comprehensive test plans for each release, which cover functional and non-functional requirements. • Design and implement automated and manual test scripts for both short-term and long-term needs. • Conduct unit, integration and performance tests using various tools and frameworks. • Provide regular status updates on testing progress and issues. • Identify and track software defects and work with developers to resolve them. • Ensure compliance with quality standards and best practices throughout the testing process. • Support user acceptance testing (UAT) activities. • Execute ad hoc queries and perform exploratory testing as needed. Qualifications: • Polytechnic or Bachelor's degree in Computer Science, Finance, Business Administration or related field. • Experience in IT testing methodologies, tools and techniques is preferred. • Experience in designing and implementing test automation solutions is preferred • Familiarity with Agile development methodologies. • Good communication skills and ability to interact effectively with cross-functional teams. • Ability to analyze complex problems and propose innovative solutions. • Excellent attention to detail and strong organizational skills. Banking Domain/Application Knowledge: - Banking Knowledge: Wealth Management; Single Portfolio View; Retail Banking Mass Market; Premier Banking; Private Banking; Priority Banking - Systems: AS400 - Wealth Product Software: Temenos Wealthsuite product Version R23/24 (TAP Core; TAP components like Wealth suite channels or WUI, WTX/ITX, Actuate, Odata)

--------------------------------------------------------------------------------

Index 752:
RESPONDSIBLE FOR DESIGN, EXECUTION AND MANAGING PROJECTS. ABLE TO INTERFACE WITH CLIENTS, CONSULTANTS AND SUB-CONTRACTOR. EXCELLENT ABILITY TO MANAGE INTERNAL AND EXTERNAL TEAMS. MIN. 1 YEAR LOCAL EXPERIENCES. GRADUATED FROM A UNIVERSITY THAT IS RECOGNISED BY SINGAPORE BOARD OF ARCHITECTS. MUST BE EXPERIENCED WITH ARCHICAD & PHOTOSHOP SOFTWARE.

--------------------------------------------------------------------------------

Index 1576:
🚫 No experience needed | 💸 No income cap Tired of waiting years for a promotion? Here, results = rewards. ✨ Benefits 💰 High commission structure 🎓 Full training & mentorship 🚀 Fast-track career progression ✈️ Travel & exposure opportunities 🎉 Fun, young & supportive team 🎯 Ideal candidates ✅ Fresh graduates ✅ ORD ✅ Career switchers ✅ Ambitious & self-motivated individuals 💥 Your income grows as fast as you do.

--------------------------------------------------------------------------------

In [13]:
manual_updates = {
    111: "Meetings, Incentives, Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Programme Delivery | Engagement Planning | Business Relationship Building",
    491: "Human Resource Systems Management | Talent Capability Assessment | Selection Management | Programme Delivery",
    645: "Audit and Compliance | Audit and Review Management | Fund Accounting | Client Management | Financial Reporting | Personal Finance Advisory | Financial Statements Review | Capital Management | Financial Acumen | Account Management | Trade Processing, Fund Settlement and Treasury Transaction Processing | People and Relationship Management" ,
    675: "User Testing and Usability Testing | Software Testing | Test Planning | Financial Analysis | Product Development | Agile Software Development | Infrastructure Support | Systems Design | Business Planning | Financial Transactions | Automation Design | Applications Development | Business Process Analysis | Project Integration | Organisational Design | Wealth Planning Administration | User Interface Design | Equipment and Systems Testing | Applications Integration | Job Analysis and Evaluation | Portfolio and Investment Risk Management | Innovation Management | New Product Introduction",

}

for idx, skills in manual_updates.items():
    mcf_skills.at[idx, "extracted_skills"] = skills
    mcf_skills.at[idx, "done"] = "manual"

In [14]:
manual_updates_tools = {
    675: "SQL | Rational Application Developer (RAD)"
}

for idx, tools in manual_updates_tools.items():
    mcf_skills.at[idx, "extracted_apps_tools"] = tools
    mcf_skills.at[idx, "done"] = "manual"

Index 555 & 1576 actually dont have any skills, so these 2 rows will be dropped

In [15]:
mcf_skills.loc[mask, ].head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
111,07875a80d2aaf783c2dceba1cf7091f2,Event Activation Representative (Entry Level),Event Activation Representative (Entry Level),<p>🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? ...,🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? NO ...,0,"[""Lead Generation"", ""Excellent Communication S...","[""Marketing / Public Relations""]","[""Temporary"", ""Full Time""]","[""Fresh/entry level""]","Meetings, Incentives, Conferences and Exhibiti...",NaN,manual
491,28a10008ca736207c901456a0beb9688,HR Recruitment Executive ( Entry Level ) #HCT,HR Recruitment Executive ( Entry Level ) #HCT,<p><em>We pride ourselves to provide quality s...,We pride ourselves to provide quality services...,0,"[""Advertising"", ""Social Media"", ""Telephone Man...","[""Healthcare / Pharmaceutical""]","[""Contract"", ""Part Time"", ""Permanent"", ""Full T...","[""Fresh/entry level""]",Human Resource Systems Management | Talent Cap...,NaN,manual
555,a4f79610a004066a25590f5a0c6e52ee,Research Fellow (Nanomaterials & Quantum Dot O...,Research Fellow (Nanomaterials & Quantum Dot O...,<p>CINTRA is a French-Singaporean joint resear...,CINTRA is a French-Singaporean joint research ...,0,"[""Higher Education"", ""Materials Science"", ""Sci...","[""Sciences / Laboratory / R&D""]","[""Contract"", ""Full Time""]","[""Professional""]",NaN,NaN,error: Skills download failed.
645,110900226420b0d243eae09cbc53e189,[2026 Intake] Assurance (Financial Services) A...,[2026 Intake] Assurance (Financial Services) A...,"<p>At Baker Tilly Singapore, we welcome highly...","At Baker Tilly Singapore, we welcome highly mo...",0,"[""Due Diligence"", ""Assurance"", ""Risk Managemen...","[""Accounting / Auditing / Taxation""]","[""Full Time""]","[""Fresh/entry level""]",Audit and Compliance | Audit and Review Manage...,NaN,manual
675,dbdb950df1b46076ad8245838eb8152e,Software Quality & Manual Testing (UAT / SIT) ...,Software Quality & Manual Testing (UAT / SIT) ...,<p>Recruiter Comments:</p>\r\n<p>- Poly grads ...,"Recruiter Comments: - Poly grads are welcomed,...",1,"[""Wealth Management"", ""UAT"", ""Confluence"", ""fu...","[""Banking and Finance"", ""Information Technolog...","[""Contract"", ""Full Time""]","[""Fresh/entry level""]",User Testing and Usability Testing | Software ...,SQL | Rational Application Developer (RAD),manual

In [16]:
mcf_skills.drop(index=[555, 1576], inplace=True)
mcf_skills.to_csv("data/mcf_entrylevel.csv", index=False)

# Remove the remaining emojis in 

Didn't manage to remove that in the first round of cleaning

In [17]:
df = pd.read_csv('data/mcf_entrylevel.csv')

In [18]:
df.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

## remove from description

In [19]:
import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["                       # start character class
        "\U0001F600-\U0001F64F"   # emoticons
        "\U0001F300-\U0001F5FF"   # symbols & pictographs
        "\U0001F680-\U0001F6FF"   # transport & map symbols
        "\U0001F1E0-\U0001F1FF"   # flags
        "\U00002700-\U000027BF"   # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', str(text))

# clean the description column
df['description'] = df['description'].apply(remove_emojis)

In [20]:
df.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,We’re Hiring: Veterinary Nurse Location: Holl...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

the emoji in row 3 is removed after running

In [21]:
df.tail()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
1582,5997b3eeac3edbf61b881117e3086a98,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Lead Generation"",...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Delivery | Customer Management | Coachin...,NaN,error: Section 'extracted_apps_and_tools' not ...
1583,49a9476ace8427dd51d829be014e3b9b,Sales Executive (Manufacturing / Construction ...,Sales Executive (Manufacturing / Construction ...,<ul><li><strong>Well Established Company</stro...,Well Established Company Basic $ 3500 - $ 4500...,1,"[""Product Knowledge"", ""Negotiation"", ""Market R...","[""Building and Construction"", ""Others""]","[""Permanent"", ""Full Time""]","[""Junior Executive""]",Technical Sales Support | Sales Management | S...,AutoCAD,success
1584,c66aaa3d3934826a0ad6d163a3eeb79b,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Customer Management | Performance Management |...,NaN,error: Section 'extracted_apps_and_tools' not ...
1585,f7fcb794db5767a1eb03d5435572f7f2,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Sales"", ""Leadersh...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Strategy | Customer Management | Sales D...,NaN,error: Section 'extracted_apps_and_tools' not ...
1586,ecea94ed9e208e4b4447550256713733,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Management | Onboarding | Total Rewards ...,NaN,error: Section 'extracted_apps_and_tools' not ...

## Remove from title

In [ ]:
# clean the title column
df['title'] = df['title'].apply(remove_emojis)

In [24]:
df.tail()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
1582,5997b3eeac3edbf61b881117e3086a98,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,SALES CONSULTANT - ENTRY LEVEL,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Lead Generation"",...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Delivery | Customer Management | Coachin...,NaN,error: Section 'extracted_apps_and_tools' not ...
1583,49a9476ace8427dd51d829be014e3b9b,Sales Executive (Manufacturing / Construction ...,Sales Executive (Manufacturing / Construction ...,<ul><li><strong>Well Established Company</stro...,Well Established Company Basic $ 3500 - $ 4500...,1,"[""Product Knowledge"", ""Negotiation"", ""Market R...","[""Building and Construction"", ""Others""]","[""Permanent"", ""Full Time""]","[""Junior Executive""]",Technical Sales Support | Sales Management | S...,AutoCAD,success
1584,c66aaa3d3934826a0ad6d163a3eeb79b,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,ENTRY-LEVEL SALES EXECUTIVE,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Customer Management | Performance Management |...,NaN,error: Section 'extracted_apps_and_tools' not ...
1585,f7fcb794db5767a1eb03d5435572f7f2,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,SALES ADVISOR – ENTRY LEVEL,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Sales"", ""Leadersh...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Strategy | Customer Management | Sales D...,NaN,error: Section 'extracted_apps_and_tools' not ...
1586,ecea94ed9e208e4b4447550256713733,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,SALES EXECUTIVE – ENTRY LEVEL,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Management | Onboarding | Total Rewards ...,NaN,error: Section 'extracted_apps_and_tools' not ...

In [25]:
# save 
df.to_csv('data/mcf_entrylevel.csv', index=False)