In [1]:
import pandas as pd
import numpy as np

In [119]:
mcf= pd.read_csv("data/mcf_clean_data.csv")
len(mcf)

22719

In [120]:
mcf.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
1,705309ff2a8d68b7ee215b6e2fc420ab,Manager (Facilities Management),Manager (Facilities Management),<p><strong >Role Overview</strong></p><p>We ar...,Role Overview We are seeking a Facilities Mana...,8,"[""Fire Safety"", ""Management Skills"", ""Sustaina...","[""Real Estate / Property Management""]","[""Permanent""]","[""Manager""]"
2,4a68226fc8b1d6f39bcf78451f7bc198,Sales Administrator,Sales Administrator,<ul>\n <li>Serve as administrator / key opera...,Serve as administrator / key operator for all ...,1,"[""Sales"", ""Microsoft Office"", ""Microsoft Excel...","[""Hospitality"", ""Sales / Retail""]","[""Full Time""]","[""Executive""]"
3,4726f24811127db6967fd1c07ec7ae77,Assistant Field Engineer(Construction),Assistant Field Engineer(Construction),<h3><strong>Our Company:</strong></h3>\n<p>Our...,Our Company: Our company develops ICT(Informat...,1,"[""Troubleshooting"", ""Construction"", ""Hardware""...","[""Customer Service"", ""Engineering"", ""Professio...","[""Full Time""]","[""Fresh/entry level""]"
4,301389565abb7d8ddd32efebb58776cf,Electronic Keyboard Teacher,Electronic Keyboard Teacher,<ul>\n <li>Teaching lessons to students at al...,Teaching lessons to students at all skill leve...,1,"[""Piano"", ""Classical"", ""Microsoft Excel"", ""Tea...","[""Education and Training""]","[""Full Time""]","[""Non-executive""]"

In [121]:
mcf.dtypes

uuid                      object
raw_title                 object
title                     object
raw_description           object
description               object
minimumYearsExperience     int64
skills                    object
categories                object
employmentTypes           object
positionLevels            object
dtype: object

In [122]:
mcf["positionLevels"].unique()

array(['["Junior Executive"]', '["Manager"]', '["Executive"]',
       '["Fresh/entry level"]', '["Non-executive"]', '["Professional"]',
       '["Senior Executive"]', '["Senior Management"]',
       '["Middle Management"]', '["Manager", "Executive"]',
       '["Middle Management", "Manager"]',
       '["Non-executive", "Fresh/entry level"]',
       '["Executive", "Fresh/entry level"]',
       '["Senior Management", "Manager"]'], dtype=object)

### Filter entry level and jobs with bachelor's degree

In [123]:
keywords = r"bachelor|degree|graduate|university|undergraduate|tertiary"
levels = r'"Fresh/entry level"|"Junior Executive"'

mcf_filtered1 = mcf[
    (
        (mcf["minimumYearsExperience"] == 0) |
        (mcf["positionLevels"].str.contains(levels, case=False, na=False))
    )
    &
    (mcf["description"].str.contains(keywords, case=False, na=False))
     & 
    (mcf["minimumYearsExperience"]<4)
   
]

mcf_filtered1.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]"
11,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]"
50,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]"
57,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]"
70,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]"

In [124]:
len(mcf_filtered1)

1589

In [125]:
mcf_filtered1["minimumYearsExperience"].value_counts()

minimumYearsExperience
0    732
1    459
2    275
3    123
Name: count, dtype: int64

In [126]:
mcf_filtered1["positionLevels"].unique()

array(['["Junior Executive"]', '["Fresh/entry level"]',
       '["Professional"]', '["Non-executive"]', '["Senior Executive"]',
       '["Executive"]', '["Manager"]',
       '["Non-executive", "Fresh/entry level"]'], dtype=object)

### Save dataset

In [127]:
mcf_filtered1.to_csv("data/mcf_entrylevel.csv", index=False)

# check skills extracted from skills from skills future

In [2]:
mcf_skills= pd.read_csv("data/mcf_entrylevel.csv")
len(mcf_skills)

1589

In [5]:
mcf_skills.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

In [6]:
mcf_skills.tail()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
1584,5997b3eeac3edbf61b881117e3086a98,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Lead Generation"",...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Delivery | Customer Management | Coachin...,NaN,error: Section 'extracted_apps_and_tools' not ...
1585,49a9476ace8427dd51d829be014e3b9b,Sales Executive (Manufacturing / Construction ...,Sales Executive (Manufacturing / Construction ...,<ul><li><strong>Well Established Company</stro...,Well Established Company Basic $ 3500 - $ 4500...,1,"[""Product Knowledge"", ""Negotiation"", ""Market R...","[""Building and Construction"", ""Others""]","[""Permanent"", ""Full Time""]","[""Junior Executive""]",Technical Sales Support | Sales Management | S...,AutoCAD,success
1586,c66aaa3d3934826a0ad6d163a3eeb79b,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Customer Management | Performance Management |...,NaN,error: Section 'extracted_apps_and_tools' not ...
1587,f7fcb794db5767a1eb03d5435572f7f2,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Sales"", ""Leadersh...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Strategy | Customer Management | Sales D...,NaN,error: Section 'extracted_apps_and_tools' not ...
1588,ecea94ed9e208e4b4447550256713733,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Management | Onboarding | Total Rewards ...,NaN,error: Section 'extracted_apps_and_tools' not ...

## NA for both skills and tools

In [10]:
mask = (
    mcf_skills["extracted_skills"].fillna("").astype(str).str.strip().eq("")
    & mcf_skills["extracted_apps_tools"].fillna("").astype(str).str.strip().eq("")
)

print("Any rows with both empty?", mask.any())
print("Number of such rows:", mask.sum())

mcf_skills.loc[mask, ].head()

Any rows with both empty? True
Number of such rows: 7

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
111,07875a80d2aaf783c2dceba1cf7091f2,Event Activation Representative (Entry Level),Event Activation Representative (Entry Level),<p>🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? ...,🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? NO ...,0,"[""Lead Generation"", ""Excellent Communication S...","[""Marketing / Public Relations""]","[""Temporary"", ""Full Time""]","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...
491,28a10008ca736207c901456a0beb9688,HR Recruitment Executive ( Entry Level ) #HCT,HR Recruitment Executive ( Entry Level ) #HCT,<p><em>We pride ourselves to provide quality s...,We pride ourselves to provide quality services...,0,"[""Advertising"", ""Social Media"", ""Telephone Man...","[""Healthcare / Pharmaceutical""]","[""Contract"", ""Part Time"", ""Permanent"", ""Full T...","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...
555,a4f79610a004066a25590f5a0c6e52ee,Research Fellow (Nanomaterials & Quantum Dot O...,Research Fellow (Nanomaterials & Quantum Dot O...,<p>CINTRA is a French-Singaporean joint resear...,CINTRA is a French-Singaporean joint research ...,0,"[""Higher Education"", ""Materials Science"", ""Sci...","[""Sciences / Laboratory / R&D""]","[""Contract"", ""Full Time""]","[""Professional""]",NaN,NaN,error: Skills download failed.
645,110900226420b0d243eae09cbc53e189,[2026 Intake] Assurance (Financial Services) A...,[2026 Intake] Assurance (Financial Services) A...,"<p>At Baker Tilly Singapore, we welcome highly...","At Baker Tilly Singapore, we welcome highly mo...",0,"[""Due Diligence"", ""Assurance"", ""Risk Managemen...","[""Accounting / Auditing / Taxation""]","[""Full Time""]","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...
675,dbdb950df1b46076ad8245838eb8152e,Software Quality & Manual Testing (UAT / SIT) ...,Software Quality & Manual Testing (UAT / SIT) ...,<p>Recruiter Comments:</p>\r\n<p>- Poly grads ...,"Recruiter Comments: - Poly grads are welcomed,...",1,"[""Wealth Management"", ""UAT"", ""Confluence"", ""fu...","[""Banking and Finance"", ""Information Technolog...","[""Contract"", ""Full Time""]","[""Fresh/entry level""]",NaN,NaN,error: Section 'extracted_skills' not found in...

Check on skills future website if actually no skills extracted

In [12]:
for idx, desc in mcf_skills.loc[mask, "description"].items():
    print(f"\nIndex {idx}:\n{desc}\n")
    print("-" * 80)

Index 111:
🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? NO WORRIES! Join the frontlines of exciting events! 🚀 What’s In It For You • 🎉 Live Campaign Activations – Bring events to life for top brands. • 🤝 Client-Facing Experience – Build relationships face-to-face. • 🕴 Sharpen Presentation Skills – Learn from experienced mentors. Why You’ll Love It Here: • ✨ Training provided, no background needed. • 👯‍♀ Work with a fun, motivated team. • 🎊 Active, engaging role – never boring. 💸 Weekly Pay + Commission Bonuses! Plus: • 📈 Level-up training and growth plans. • 🧠 Opportunities to lead future activations. • ✈ Travel perks for standout performers.

--------------------------------------------------------------------------------

Index 491:
We pride ourselves to provide quality services as a leading recruitment consultancy in Singapore. We are looking for dynamic, driven and focus individual to join our distinctive team in driving the business development strategy and recruitment processes for our clients. If you think you can take up the challenge as a professional Recruitment Consultant in this ‘people oriented’ field, do not hesitate, come and join us! Responsibilities: • Identify and assess potential candidates • Conduct interview and manage selection procedures • Design job descriptions and interview questions • Organize and attend recruitment events • Lead discussions in quarterly and annual hiring needs by department • Foster long-term relationships with past applicants and potential candidates • Involve actively in Human Resource activities with regards to Hiring and Managing of potential candidates Requirements: • Degree in any Discipline • Candidates with strong track record in sports or co-curricular activities will have an added advantage • Candidate with great team spirit, persistency, good communication and interpersonal skills are welcome to apply Interested candidates please send in your resume to: clinicalresearch@recruitexpress.com.sg EA Personnel: Valerie Yong Kian Fung CEI No.: R1103704 Recruit Express Pte Ltd, EA License No.: 99C4599

--------------------------------------------------------------------------------

Index 555:
CINTRA is a French-Singaporean joint research laboratory, a CNRS International Research Laboratory under the French Ministry of Higher Education and Research. It is a collaboration between the French National Centre for Scientific Research (CNRS), Nanyang Technological University (NTU) and Thales, bringing together researchers and students from France and Singapore. The research focus of this joint laboratory is towards the development of innovative nanotechnologies and nanomaterials for various electronic and photonic applications. We are looking for a Research Fellow that will lead advanced research on halide perovskite quantum dots (PQDs) for optoelectronic and display applications. The role focuses on the design, synthesis, stabilization, and integration of PQDs into polymer-based color conversion layers. The successful candidate will develop robust PQD/polymer composite films, optimize scalable film fabrication processes, and perform comprehensive optical and structural characterization. Key Responsibilities: Investigating degradation mechanisms, improving material stability and performance, and collaborating with interdisciplinary research teams. Contribute to high-impact publications, mentor junior researchers, and support laboratory operations and safety. Job Requirements: PhD in Chemistry, Materials Science, or a closely related field. Demonstrated expertise in perovskite quantum dot synthesis and stabilization strategies. Strong experience with optical and structural characterization techniques. Proven ability to fabricate and optimize polymer-based nanocomposite films. Effective problem-solving skills. ​ We regret that only shortlisted candidates will be notified.

--------------------------------------------------------------------------------

Index 645:
At Baker Tilly Singapore, we welcome highly motivated and committed individuals who share our core values to join us. We are committed to our values of leading by example, delivering quality services with integrity, communicating openly, acting ethically, and fostering a community built around civic responsibility and teamwork. We are looking for an Assurance (Financial Services) Associate, who will be involved in various sizes of financial services audit engagements which include planning, performing, and concluding the engagement. The Assurance Associate will be exposed to a broad range of capital markets entities and investment funds such as private equities, real estate, mutual funds, variable capital companies, etc. In this role, you will: • Involvement in a broad range of statutory and regulatory audit assignments for our financial services clients • Assist in obtaining all necessary audit working papers and documentation including researching and documenting facts and findings • Identify and communicate accounting and auditing matters to managers and partners • Identify performance improvement opportunities • Interact with clients to help ensure that the information flow from the client to the audit team is efficient We are looking for people with the following: • Graduates with an Accountancy degree or equivalent professional qualification in Accountancy • Accountancy undergraduates in the final year of study are welcome to apply • Good command of the English language • Strong interpersonal and client relationship skills

--------------------------------------------------------------------------------

Index 675:
Recruiter Comments: - Poly grads are welcomed, can be fresh graduates, good working attitude, logical and analytical thinking - Writing of test cases (can be trained) - Good to have Jira, SQL not required Job Description Your role will require close collaboration across multiple areas within the organization including but not limited to: 1. Project Management Office (PMO) 2. Information Technology (IT) 3. Product Development & Strategy (PD&S) 4. Business Units / Divisions (BU/Ds) 5. Operations (Ops) 6. Risk Management 8. Other relevant units as needed You will need to develop expertise in understanding the business processes and functions supported by the new system as well as conduct detailed reviews of user requirements and specifications. You will also need to develop and execute test plans, procedures and scenarios to ensure that the system meets all requirements and works seamlessly with other systems. Responsibilities: • Define, develop, document, execute and report on test approaches and plans. • Collaborate closely with project teams as well as other relevant stakeholders such as end users, subject matter experts, technical teams etc. • Develop and maintain comprehensive test plans for each release, which cover functional and non-functional requirements. • Design and implement automated and manual test scripts for both short-term and long-term needs. • Conduct unit, integration and performance tests using various tools and frameworks. • Provide regular status updates on testing progress and issues. • Identify and track software defects and work with developers to resolve them. • Ensure compliance with quality standards and best practices throughout the testing process. • Support user acceptance testing (UAT) activities. • Execute ad hoc queries and perform exploratory testing as needed. Qualifications: • Polytechnic or Bachelor's degree in Computer Science, Finance, Business Administration or related field. • Experience in IT testing methodologies, tools and techniques is preferred. • Experience in designing and implementing test automation solutions is preferred • Familiarity with Agile development methodologies. • Good communication skills and ability to interact effectively with cross-functional teams. • Ability to analyze complex problems and propose innovative solutions. • Excellent attention to detail and strong organizational skills. Banking Domain/Application Knowledge: - Banking Knowledge: Wealth Management; Single Portfolio View; Retail Banking Mass Market; Premier Banking; Private Banking; Priority Banking - Systems: AS400 - Wealth Product Software: Temenos Wealthsuite product Version R23/24 (TAP Core; TAP components like Wealth suite channels or WUI, WTX/ITX, Actuate, Odata)

--------------------------------------------------------------------------------

Index 752:
RESPONDSIBLE FOR DESIGN, EXECUTION AND MANAGING PROJECTS. ABLE TO INTERFACE WITH CLIENTS, CONSULTANTS AND SUB-CONTRACTOR. EXCELLENT ABILITY TO MANAGE INTERNAL AND EXTERNAL TEAMS. MIN. 1 YEAR LOCAL EXPERIENCES. GRADUATED FROM A UNIVERSITY THAT IS RECOGNISED BY SINGAPORE BOARD OF ARCHITECTS. MUST BE EXPERIENCED WITH ARCHICAD & PHOTOSHOP SOFTWARE.

--------------------------------------------------------------------------------

Index 1576:
🚫 No experience needed | 💸 No income cap Tired of waiting years for a promotion? Here, results = rewards. ✨ Benefits 💰 High commission structure 🎓 Full training & mentorship 🚀 Fast-track career progression ✈️ Travel & exposure opportunities 🎉 Fun, young & supportive team 🎯 Ideal candidates ✅ Fresh graduates ✅ ORD ✅ Career switchers ✅ Ambitious & self-motivated individuals 💥 Your income grows as fast as you do.

--------------------------------------------------------------------------------

In [13]:
manual_updates = {
    111: "Meetings, Incentives, Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Programme Delivery | Engagement Planning | Business Relationship Building",
    491: "Human Resource Systems Management | Talent Capability Assessment | Selection Management | Programme Delivery",
    645: "Audit and Compliance | Audit and Review Management | Fund Accounting | Client Management | Financial Reporting | Personal Finance Advisory | Financial Statements Review | Capital Management | Financial Acumen | Account Management | Trade Processing, Fund Settlement and Treasury Transaction Processing | People and Relationship Management" ,
    675: "User Testing and Usability Testing | Software Testing | Test Planning | Financial Analysis | Product Development | Agile Software Development | Infrastructure Support | Systems Design | Business Planning | Financial Transactions | Automation Design | Applications Development | Business Process Analysis | Project Integration | Organisational Design | Wealth Planning Administration | User Interface Design | Equipment and Systems Testing | Applications Integration | Job Analysis and Evaluation | Portfolio and Investment Risk Management | Innovation Management | New Product Introduction",

}

for idx, skills in manual_updates.items():
    mcf_skills.at[idx, "extracted_skills"] = skills
    mcf_skills.at[idx, "done"] = "manual"

In [14]:
manual_updates_tools = {
    675: "SQL | Rational Application Developer (RAD)"
}

for idx, tools in manual_updates_tools.items():
    mcf_skills.at[idx, "extracted_apps_tools"] = tools
    mcf_skills.at[idx, "done"] = "manual"

Index 555 & 1576 actually dont have any skills, I decided to remove them because:

index 555 is actually a role for phd gradute so not applicable for this project

index 1576 description does not even describe the job contents so not applicable for this project as well

In [15]:
mcf_skills.loc[mask, ].head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
111,07875a80d2aaf783c2dceba1cf7091f2,Event Activation Representative (Entry Level),Event Activation Representative (Entry Level),<p>🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? ...,🎓 JUST GRADUATED? ORD DONE? NO EXPERIENCE? NO ...,0,"[""Lead Generation"", ""Excellent Communication S...","[""Marketing / Public Relations""]","[""Temporary"", ""Full Time""]","[""Fresh/entry level""]","Meetings, Incentives, Conferences and Exhibiti...",NaN,manual
491,28a10008ca736207c901456a0beb9688,HR Recruitment Executive ( Entry Level ) #HCT,HR Recruitment Executive ( Entry Level ) #HCT,<p><em>We pride ourselves to provide quality s...,We pride ourselves to provide quality services...,0,"[""Advertising"", ""Social Media"", ""Telephone Man...","[""Healthcare / Pharmaceutical""]","[""Contract"", ""Part Time"", ""Permanent"", ""Full T...","[""Fresh/entry level""]",Human Resource Systems Management | Talent Cap...,NaN,manual
555,a4f79610a004066a25590f5a0c6e52ee,Research Fellow (Nanomaterials & Quantum Dot O...,Research Fellow (Nanomaterials & Quantum Dot O...,<p>CINTRA is a French-Singaporean joint resear...,CINTRA is a French-Singaporean joint research ...,0,"[""Higher Education"", ""Materials Science"", ""Sci...","[""Sciences / Laboratory / R&D""]","[""Contract"", ""Full Time""]","[""Professional""]",NaN,NaN,error: Skills download failed.
645,110900226420b0d243eae09cbc53e189,[2026 Intake] Assurance (Financial Services) A...,[2026 Intake] Assurance (Financial Services) A...,"<p>At Baker Tilly Singapore, we welcome highly...","At Baker Tilly Singapore, we welcome highly mo...",0,"[""Due Diligence"", ""Assurance"", ""Risk Managemen...","[""Accounting / Auditing / Taxation""]","[""Full Time""]","[""Fresh/entry level""]",Audit and Compliance | Audit and Review Manage...,NaN,manual
675,dbdb950df1b46076ad8245838eb8152e,Software Quality & Manual Testing (UAT / SIT) ...,Software Quality & Manual Testing (UAT / SIT) ...,<p>Recruiter Comments:</p>\r\n<p>- Poly grads ...,"Recruiter Comments: - Poly grads are welcomed,...",1,"[""Wealth Management"", ""UAT"", ""Confluence"", ""fu...","[""Banking and Finance"", ""Information Technolog...","[""Contract"", ""Full Time""]","[""Fresh/entry level""]",User Testing and Usability Testing | Software ...,SQL | Rational Application Developer (RAD),manual

In [16]:
mcf_skills.drop(index=[555, 1576], inplace=True)
mcf_skills.to_csv("data/mcf_entrylevel.csv", index=False)

## NA for skills

In [53]:
df = pd.read_csv("data/mcf_entrylevel.csv")

# rows where extracted_skills is missing
na_rows = df[df["extracted_skills"].isna()]

In [54]:
na_rows

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
751,30d38911187b8c345cd04c7b000062e1,ARCHITECTURAL ASSISTANT,ARCHITECTURAL ASSISTANT,"<p>RESPONDSIBLE FOR DESIGN, EXECUTION AND MANA...","RESPONDSIBLE FOR DESIGN, EXECUTION AND MANAGIN...",1,"[""Construction"", ""BIM"", ""Architect"", ""Architec...","[""Architecture / Interior Design""]","[""Full Time""]","[""Junior Executive""]",NaN,NaN,error: Skills download failed.

In [58]:
for i, desc in na_rows["description"].items():
    print(f"Row {i}:\n{desc}\n{'-'*80}")

Row 751:
RESPONDSIBLE FOR DESIGN, EXECUTION AND MANAGING PROJECTS. ABLE TO INTERFACE WITH CLIENTS, CONSULTANTS AND SUB-CONTRACTOR. EXCELLENT ABILITY TO MANAGE INTERNAL AND EXTERNAL TEAMS. MIN. 1 YEAR LOCAL EXPERIENCES. GRADUATED FROM A UNIVERSITY THAT IS RECOGNISED BY SINGAPORE BOARD OF ARCHITECTS. MUST BE EXPERIENCED WITH ARCHICAD & PHOTOSHOP SOFTWARE.
--------------------------------------------------------------------------------

I think the description is too vague that is why skills future website did not output any skills, but it can still be kept since it mentioned apps & tools needed which could be used to train the model.

As for whether the job requires any skills, a human also not 100% sure since its descriptio is vague

# Remove the remaining emojis in 

Didn't manage to remove that in the first round of cleaning

In [17]:
df = pd.read_csv('data/mcf_entrylevel.csv')

In [18]:
df.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,🐾 We’re Hiring: Veterinary Nurse Location: Hol...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

## remove from description

In [19]:
import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["                       # start character class
        "\U0001F600-\U0001F64F"   # emoticons
        "\U0001F300-\U0001F5FF"   # symbols & pictographs
        "\U0001F680-\U0001F6FF"   # transport & map symbols
        "\U0001F1E0-\U0001F1FF"   # flags
        "\U00002700-\U000027BF"   # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', str(text))

# clean the description column
df['description'] = df['description'].apply(remove_emojis)

In [20]:
df.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,We’re Hiring: Veterinary Nurse Location: Holl...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

the emoji in row 3 is removed after running

In [21]:
df.tail()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
1582,5997b3eeac3edbf61b881117e3086a98,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Lead Generation"",...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Delivery | Customer Management | Coachin...,NaN,error: Section 'extracted_apps_and_tools' not ...
1583,49a9476ace8427dd51d829be014e3b9b,Sales Executive (Manufacturing / Construction ...,Sales Executive (Manufacturing / Construction ...,<ul><li><strong>Well Established Company</stro...,Well Established Company Basic $ 3500 - $ 4500...,1,"[""Product Knowledge"", ""Negotiation"", ""Market R...","[""Building and Construction"", ""Others""]","[""Permanent"", ""Full Time""]","[""Junior Executive""]",Technical Sales Support | Sales Management | S...,AutoCAD,success
1584,c66aaa3d3934826a0ad6d163a3eeb79b,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Customer Management | Performance Management |...,NaN,error: Section 'extracted_apps_and_tools' not ...
1585,f7fcb794db5767a1eb03d5435572f7f2,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Sales"", ""Leadersh...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Strategy | Customer Management | Sales D...,NaN,error: Section 'extracted_apps_and_tools' not ...
1586,ecea94ed9e208e4b4447550256713733,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Management | Onboarding | Total Rewards ...,NaN,error: Section 'extracted_apps_and_tools' not ...

## Remove from title

In [ ]:
# clean the title column
df['title'] = df['title'].apply(remove_emojis)

In [24]:
df.tail()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
1582,5997b3eeac3edbf61b881117e3086a98,⚡🌟 SALES CONSULTANT - ENTRY LEVEL 🌟,SALES CONSULTANT - ENTRY LEVEL,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Lead Generation"",...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Delivery | Customer Management | Coachin...,NaN,error: Section 'extracted_apps_and_tools' not ...
1583,49a9476ace8427dd51d829be014e3b9b,Sales Executive (Manufacturing / Construction ...,Sales Executive (Manufacturing / Construction ...,<ul><li><strong>Well Established Company</stro...,Well Established Company Basic $ 3500 - $ 4500...,1,"[""Product Knowledge"", ""Negotiation"", ""Market R...","[""Building and Construction"", ""Others""]","[""Permanent"", ""Full Time""]","[""Junior Executive""]",Technical Sales Support | Sales Management | S...,AutoCAD,success
1584,c66aaa3d3934826a0ad6d163a3eeb79b,⚡⚡️ ENTRY-LEVEL SALES EXECUTIVE ⚡️,ENTRY-LEVEL SALES EXECUTIVE,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Customer Management | Performance Management |...,NaN,error: Section 'extracted_apps_and_tools' not ...
1585,f7fcb794db5767a1eb03d5435572f7f2,⚡🌟 SALES ADVISOR – ENTRY LEVEL 🌟,SALES ADVISOR – ENTRY LEVEL,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Coaching"", ""Sales"", ""Leadersh...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Strategy | Customer Management | Sales D...,NaN,error: Section 'extracted_apps_and_tools' not ...
1586,ecea94ed9e208e4b4447550256713733,⚡🚀 SALES EXECUTIVE – ENTRY LEVEL 🚀,SALES EXECUTIVE – ENTRY LEVEL,<p>Training Provided | High Commission | Uncap...,Training Provided | High Commission | Uncapped...,0,"[""Negotiation"", ""Mentoring"", ""Management Skill...","[""Events / Promotions"", ""General Management"", ...","[""Permanent"", ""Full Time""]","[""Fresh/entry level""]",Sales Management | Onboarding | Total Rewards ...,NaN,error: Section 'extracted_apps_and_tools' not ...

In [25]:
# save 
df.to_csv('data/mcf_entrylevel.csv', index=False)

# check that extracted skills match the skills taxonomy

## clean up the skills taxonomy

In [26]:
from pathlib import Path

input_path = Path("data/raw/jobsandskills-skillsfuture-unique-skills-list.xlsx")
output_path = Path("data/skills_taxo.csv")

df = pd.read_excel(
    input_path,
    sheet_name="Unique Skills List",
    usecols=["parent_skill_title", "parent_skill_description"],
)

df = df.dropna(subset=["parent_skill_title"]).drop_duplicates()

df.to_csv(output_path, index=False, encoding="utf-8-sig")
print(f"Saved {len(df)} rows to {output_path}")

Saved 2201 rows to data\skills_taxo.csv

# Check that each extracted skill match the parent skill title in skill taxonomy
It’s called a `token` here because each piece of extracted_skills is being treated as one split unit after you break the string on |.

In [27]:
import pandas as pd


def _solve_skill_token_sequence(tokens, taxonomy_titles, max_join=6):
    token_count = len(tokens)
    edges = {start: [(start + 1, 0, None)] for start in range(token_count)}

    for start in range(token_count):
        parts = []
        for end in range(start, min(token_count, start + max_join)):
            parts.append(tokens[end])
            candidate = ", ".join(parts)
            if candidate in taxonomy_titles:
                span = end - start + 1
                edges[start].append((end + 1, span, candidate))

    best_from = [0] * (token_count + 1)
    for start in range(token_count - 1, -1, -1):
        best_from[start] = max(weight + best_from[end] for end, weight, _ in edges[start])

    optimal_edges = {start: [] for start in range(token_count)}
    for start in range(token_count):
        for end, weight, candidate in edges[start]:
            if weight + best_from[end] == best_from[start]:
                optimal_edges[start].append((end, weight, candidate))

    ways_prefix = [0] * (token_count + 1)
    ways_prefix[0] = 1
    for start in range(token_count):
        for end, _, _ in optimal_edges[start]:
            ways_prefix[end] += ways_prefix[start]

    ways_suffix = [0] * (token_count + 1)
    ways_suffix[token_count] = 1
    for start in range(token_count - 1, -1, -1):
        ways_suffix[start] = sum(ways_suffix[end] for end, _, _ in optimal_edges[start])

    total_optimal_paths = ways_suffix[0]
    guaranteed_segments = []
    covered_positions = set()

    for start in range(token_count):
        for end, weight, candidate in optimal_edges[start]:
            if weight == 0:
                continue
            if ways_prefix[start] * ways_suffix[end] == total_optimal_paths:
                guaranteed_segments.append((start, end, candidate))
                covered_positions.update(range(start, end))

    guaranteed_segments.sort(key=lambda item: (item[0], item[1]))
    unresolved_positions = [pos for pos in range(token_count) if pos not in covered_positions]
    return guaranteed_segments, unresolved_positions


def build_skill_audit_report(
    mcf_path,
    taxo_path,
    extracted_col="extracted_skills",
    taxo_col="parent_skill_title",
    delimiter="|",
    max_join=6,
):
    jobs_df = pd.read_csv(mcf_path, encoding="utf-8-sig")
    taxo_df = pd.read_csv(taxo_path, encoding="utf-8-sig")

    taxonomy_titles = {
        str(value).strip()
        for value in taxo_df[taxo_col].dropna()
        if str(value).strip()
    }

    raw_token_rows = []
    normalized_rows = []
    manual_review_rows = []
    unique_raw_tokens = set()
    unique_unresolved_tokens = set()

    non_empty_mask = jobs_df[extracted_col].fillna("").astype(str).str.strip().ne("")

    for idx, row in jobs_df.loc[non_empty_mask].iterrows():
        raw_text = str(row[extracted_col]).strip()
        tokens = [part.strip() for part in raw_text.split(delimiter) if part.strip()]
        row_number = idx + 2
        row_id = row.get("uuid", "")
        row_title = row.get("title", "")

        for token in tokens:
            unique_raw_tokens.add(token)
            raw_token_rows.append(
                {
                    "row_number": row_number,
                    "uuid": row_id,
                    "title": row_title,
                    "raw_extracted_skills": raw_text,
                    "raw_skill": token,
                    "raw_exact_match": token in taxonomy_titles,
                }
            )

        guaranteed_segments, unresolved_positions = _solve_skill_token_sequence(
            tokens,
            taxonomy_titles,
            max_join=max_join,
        )

        for start, end, candidate in guaranteed_segments:
            normalized_rows.append(
                {
                    "row_number": row_number,
                    "uuid": row_id,
                    "title": row_title,
                    "raw_extracted_skills": raw_text,
                    "normalized_skill": candidate,
                    "source_tokens": f" {delimiter} ".join(tokens[start:end]),
                    "resolution_type": "exact" if end - start == 1 else "recombined",
                }
            )

        if unresolved_positions:
            unresolved_tokens = [tokens[pos] for pos in unresolved_positions]
            unique_unresolved_tokens.update(unresolved_tokens)
            manual_review_rows.append(
                {
                    "row_number": row_number,
                    "uuid": row_id,
                    "title": row_title,
                    "raw_extracted_skills": raw_text,
                    "unresolved_tokens": " | ".join(unresolved_tokens),
                    "resolution_type": "unresolved",
                }
            )

    raw_token_df = pd.DataFrame(raw_token_rows)
    normalized_token_df = pd.DataFrame(normalized_rows)
    manual_review_df = pd.DataFrame(manual_review_rows)

    summary = {
        "mcf_rows": len(jobs_df),
        "rows_with_extracted_skills": int(non_empty_mask.sum()),
        "taxonomy_parent_titles": len(taxonomy_titles),
        "unique_raw_tokens": len(unique_raw_tokens),
        "raw_exact_matches": sum(token in taxonomy_titles for token in unique_raw_tokens),
        "raw_exact_mismatches": sum(token not in taxonomy_titles for token in unique_raw_tokens),
        "unique_normalized_titles": int(normalized_token_df["normalized_skill"].nunique()) if not normalized_token_df.empty else 0,
        "recombined_token_count": int((normalized_token_df["resolution_type"] == "recombined").sum()) if not normalized_token_df.empty else 0,
        "manual_review_row_count": len(manual_review_df),
        "manual_review_token_count": len(unique_unresolved_tokens),
    }

    return {
        "summary": summary,
        "raw_token_df": raw_token_df,
        "normalized_token_df": normalized_token_df,
        "manual_review_df": manual_review_df,
    }

In [35]:
report = build_skill_audit_report(
    "data/mcf_entrylevel.csv",
    "data/skills_taxo.csv",
)

summary_df = pd.DataFrame(
    report["summary"].items(),
    columns=["metric", "value"],
)

raw_mismatch_df = (
    report["raw_token_df"]
    .loc[lambda df: ~df["raw_exact_match"]]
    .groupby("raw_skill", as_index=False)
    .size()
    .rename(columns={"size": "frequency"})
    .sort_values(["frequency", "raw_skill"], ascending=[False, True])
    .reset_index(drop=True)
)

recombined_df = (
    report["normalized_token_df"]
    .loc[lambda df: df["resolution_type"].eq("recombined")]
    .groupby(["source_tokens", "normalized_skill"], as_index=False)
    .size()
    .rename(columns={"source_tokens": "raw_skill", "size": "frequency"})
    .sort_values(["frequency", "normalized_skill", "raw_skill"], ascending=[False, True, True])
    .reset_index(drop=True)
)


manual_review_df = (
    report["manual_review_df"]
    .sort_values(["row_number", "title"], ascending=[True, True])
    .reset_index(drop=True)
)

In [30]:
print("Skill taxonomy audit summary")
summary_df

Skill taxonomy audit summary

                       metric  value
0                    mcf_rows   1587
1  rows_with_extracted_skills   1586
2      taxonomy_parent_titles   2201
3           unique_raw_tokens   1590
4           raw_exact_matches   1519
5        raw_exact_mismatches     71
6    unique_normalized_titles   1549
7      recombined_token_count    368
8     manual_review_row_count      3
9   manual_review_token_count      2

In [33]:
print("Raw mismatched tokens")
raw_mismatch_df

Raw mismatched tokens

                                            raw_skill  frequency
0   Fund Settlement and Treasury Transaction Proce...         48
1                                    Trade Processing         48
2                                          Electrical         44
3                  Electronic and Control Engineering         44
4                                Contract Preparation         42
..                                                ...        ...
66                     Control and Supply Restoration          1
67                           Generative AI Regulatory          1
68                                              Legal          1
69                                 Network Monitoring          1
70                     and Risk Management Compliance          1

[71 rows x 2 columns]

In [36]:
print("Normalized matches after comma-aware recombination")
recombined_df

Normalized matches after comma-aware recombination

,raw_skill,normalized_skill,frequency
0,Trade Processing | Fund Settlement and Treasur...,"Trade Processing, Fund Settlement and Treasury...",48
1,Electrical | Electronic and Control Engineering,"Electrical, Electronic and Control Engineering",44
2,Contract Preparation | Evaluation | Negotiatio...,"Contract Preparation, Evaluation, Negotiation ...",42
3,Training | Coaching and Assessment Management,"Training, Coaching and Assessment Management",39
4,Meetings | Incentives | Conferences and Exhibi...,"Meetings, Incentives, Conferences and Exhibiti...",27
5,Health | Safety and Environment Procedures Imp...,"Health, Safety and Environment Procedures Impl...",23
6,Generative AI Innovation | Research and Develo...,"Generative AI Innovation, Research and Develop...",21
7,Industry Knowledge | Research and Analysis,"Industry Knowledge, Research and Analysis",16
8,Engineering | Procurement and Construction Man...,"Engineering, Procurement and Construction Mana...",13
9,Engineering Drawing | Interpretation and Manag...,"Engineering Drawing, Interpretation and Manage...",12
10,Impact Indicators | Measurement and Reporting,"Impact Indicators, Measurement and Reporting",11
11,Work with Infected and Non-Infected Organisms ...,"Work with Infected and Non-Infected Organisms,...",10
12,Heating | Ventilation and Air Conditioning Sys...,"Heating, Ventilation and Air Conditioning Syst...",7
13,Cultural | Heritage and Socio-economic Sensiti...,"Cultural, Heritage and Socio-economic Sensitiv...",6
14,Ship Mooring | Anchoring and Securing Operations,"Ship Mooring, Anchoring and Securing Operations",5
15,Workplace Safety and Health Management in Chem...,Workplace Safety and Health Management in Chem...,5
16,Material Management (Planning | Sourcing | Use...,"Material Management (Planning, Sourcing, Use, ...",4
17,Professional | Legal and Ethical Healthcare Pr...,"Professional, Legal and Ethical Healthcare Pra...",4
18,Additive Manufacturing Standards | Qualificati...,"Additive Manufacturing Standards, Qualificatio...",3
19,Electrical Termination | Connection and Measur...,"Electrical Termination, Connection and Measure...",3
20,Ethics | Values and Legislation,"Ethics, Values and Legislation",3
21,Meetings | Incentives | Conferences and Exhibi...,"Meetings, Incentives, Conferences and Exhibiti...",3
22,Organisational Vision | Mission and Values For...,"Organisational Vision, Mission and Values Form...",3
23,Tour and Travel Coordination | Ticketing and R...,"Tour and Travel Coordination, Ticketing and Re...",3
24,Environmental Management System Policies | Sta...,"Environmental Management System Policies, Stan...",2
25,Health | Hygiene and Nutrition for Children,"Health, Hygiene and Nutrition for Children",2
26,Landscape Tools | Equipment and Machinery Mana...,"Landscape Tools, Equipment and Machinery Manag...",2
27,Measurement | Reporting and Verification (MRV)...,"Measurement, Reporting and Verification (MRV) ...",2
28,Stage | Liveshow and Theatre Action Coordination,"Stage, Liveshow and Theatre Action Coordination",2
29,Attractions Membership | Admission and Ticketi...,"Attractions Membership, Admission and Ticketin...",1
30,Generative AI Regulatory | Legal | and Risk Ma...,"Generative AI Regulatory, Legal, and Risk Mana...",1
31,Network Monitoring | Control and Supply Restor...,"Network Monitoring, Control and Supply Restora...",1

## Some skill were split by `|` when it shouldn't, so we will remove it

This happens because the skills future website used `,` in the name of a skill, so the skill name got seperated when downloading the csv from the website

In [38]:
import pandas as pd


def _solve_skill_token_sequence(tokens, taxonomy_titles, max_join=6):
    token_count = len(tokens)
    edges = {start: [(start + 1, 0, None)] for start in range(token_count)}

    for start in range(token_count):
        parts = []
        for end in range(start, min(token_count, start + max_join)):
            parts.append(tokens[end])
            candidate = ", ".join(parts)
            if candidate in taxonomy_titles:
                span = end - start + 1
                edges[start].append((end + 1, span, candidate))

    best_from = [0] * (token_count + 1)
    for start in range(token_count - 1, -1, -1):
        best_from[start] = max(weight + best_from[end] for end, weight, _ in edges[start])

    optimal_edges = {start: [] for start in range(token_count)}
    for start in range(token_count):
        for end, weight, candidate in edges[start]:
            if weight + best_from[end] == best_from[start]:
                optimal_edges[start].append((end, weight, candidate))

    ways_prefix = [0] * (token_count + 1)
    ways_prefix[0] = 1
    for start in range(token_count):
        for end, _, _ in optimal_edges[start]:
            ways_prefix[end] += ways_prefix[start]

    ways_suffix = [0] * (token_count + 1)
    ways_suffix[token_count] = 1
    for start in range(token_count - 1, -1, -1):
        ways_suffix[start] = sum(ways_suffix[end] for end, _, _ in optimal_edges[start])

    total_optimal_paths = ways_suffix[0]
    guaranteed_segments = []
    covered_positions = set()

    for start in range(token_count):
        for end, weight, candidate in optimal_edges[start]:
            if weight == 0:
                continue
            if ways_prefix[start] * ways_suffix[end] == total_optimal_paths:
                guaranteed_segments.append((start, end, candidate))
                covered_positions.update(range(start, end))

    guaranteed_segments.sort(key=lambda item: (item[0], item[1]))
    unresolved_positions = [pos for pos in range(token_count) if pos not in covered_positions]
    return guaranteed_segments, unresolved_positions


def normalize_extracted_skills(raw_text, taxonomy_titles, delimiter="|", max_join=6):
    if pd.isna(raw_text) or not str(raw_text).strip():
        return "", [], False

    raw_text = str(raw_text).strip()
    tokens = [part.strip() for part in raw_text.split(delimiter) if part.strip()]

    guaranteed_segments, unresolved_positions = _solve_skill_token_sequence(
        tokens,
        taxonomy_titles,
        max_join=max_join,
    )

    segment_by_start = {start: (end, candidate) for start, end, candidate in guaranteed_segments}

    normalized_parts = []
    pos = 0
    while pos < len(tokens):
        if pos in segment_by_start:
            end, candidate = segment_by_start[pos]
            normalized_parts.append(candidate)
            pos = end
        else:
            normalized_parts.append(tokens[pos])
            pos += 1

    normalized_text = " | ".join(normalized_parts)
    unresolved_tokens = [tokens[pos] for pos in unresolved_positions]
    changed = normalized_text != raw_text

    return normalized_text, unresolved_tokens, changed


mcf_path = "data/mcf_entrylevel.csv"
taxo_path = "data/skills_taxo.csv"

jobs_df = pd.read_csv(mcf_path, encoding="utf-8-sig")
taxo_df = pd.read_csv(taxo_path, encoding="utf-8-sig")

taxonomy_titles = {
    str(value).strip()
    for value in taxo_df["parent_skill_title"].dropna()
    if str(value).strip()
}

normalized_values = []
manual_review_rows = []
changed_rows = 0

for idx, row in jobs_df.iterrows():
    raw_value = row.get("extracted_skills", "")
    normalized_text, unresolved_tokens, changed = normalize_extracted_skills(
        raw_value,
        taxonomy_titles,
        delimiter="|",
        max_join=6,
    )

    if pd.isna(raw_value) or not str(raw_value).strip():
        normalized_values.append("")
    else:
        normalized_values.append(normalized_text)

    if changed:
        changed_rows += 1

    if unresolved_tokens:
        manual_review_rows.append(
            {
                "row_number": idx + 2,
                "uuid": row.get("uuid", ""),
                "title": row.get("title", ""),
                "unresolved_tokens": " | ".join(unresolved_tokens),
                "normalized_extracted_skills": normalized_text,
            }
        )

jobs_df["extracted_skills"] = normalized_values
jobs_df.to_csv(mcf_path, index=False, encoding="utf-8-sig")

manual_review_df = (
    pd.DataFrame(manual_review_rows)
    .sort_values(["row_number", "title"], ascending=[True, True])
    .reset_index(drop=True)
)

print(f"Updated file in place: {mcf_path}")
print(f"Rows changed: {changed_rows}")

Updated file in place: data/mcf_entrylevel.csv
Rows changed: 328

## check that it worked

In [43]:
jobs = pd.read_csv('data/mcf_entrylevel.csv')

In [44]:
jobs.head()

,uuid,raw_title,title,raw_description,description,minimumYearsExperience,skills,categories,employmentTypes,positionLevels,extracted_skills,extracted_apps_tools,done
0,0f754b51f0e412570c88adf9ecc0e872,"Assistant Manager, Corporate Communications","Assistant Manager, Corporate Communications",<p><strong>Job Summary: </strong></p><p>This r...,Job Summary: This role supports the Corporate ...,3,"[""Multimedia"", ""Social Media"", ""Strategic Comm...","[""Marketing / Public Relations""]","[""Permanent""]","[""Junior Executive""]",Public Relations Management | Mass Communicati...,NaN,error: Section 'extracted_apps_and_tools' not ...
1,91dc337d5944663301fb1b60519c5e46,Outreach Operations and Data Analysis Executive,Outreach Operations and Data Analysis Executive,<p><strong>Working Days: </strong>5 days acros...,Working Days: 5 days across Monday - Sunday Lo...,0,"[""Tableau"", ""Data Analysis"", ""Big Data"", ""Inte...","[""Customer Service""]","[""Contract""]","[""Fresh/entry level""]",Information Gathering and Analysis | Effective...,NaN,error: Section 'extracted_apps_and_tools' not ...
2,7e67478b8d6e830db5e40c417833198f,Lecturer (Digital Journalism),Lecturer (Digital Journalism),"<p>Young and research-intensive, Nanyang Techn...","Young and research-intensive, Nanyang Technolo...",0,"[""Producing"", ""Multimedia"", ""Teaching"", ""Big D...","[""Education and Training""]","[""Full Time""]","[""Professional""]",News Editing | Audience Analytics | Content Cr...,NaN,error: Section 'extracted_apps_and_tools' not ...
3,b83e84454e5aa753ab4d97b2de50480c,Vet Nurse,Vet Nurse,<p>🐾<strong> We’re Hiring: Veterinary Nurse</s...,We’re Hiring: Veterinary Nurse Location: Holl...,1,"[""Veterinary"", ""ICU"", ""Quality Improvement"", ""...","[""Healthcare / Pharmaceutical""]","[""Full Time""]","[""Junior Executive""]",Clinical Support Duties and Procedures | Canin...,NaN,error: Section 'extracted_apps_and_tools' not ...
4,2a159f1e9bb5af1b43cc12be9b7f32c6,Project Engineer,Project Engineer,<p>The Role:</p><p>The candidate will coordina...,The Role: The candidate will coordinate projec...,1,"[""Microsoft Office"", ""Construction"", ""Drawing""...","[""Engineering""]","[""Full Time""]","[""Fresh/entry level""]",Engineering Project Management | Electrical En...,NaN,error: Section 'extracted_apps_and_tools' not ...

In [46]:
def _solve_skill_token_sequence(tokens, taxonomy_titles, max_join=6):
    token_count = len(tokens)
    edges = {start: [(start + 1, 0, None)] for start in range(token_count)}

    for start in range(token_count):
        parts = []
        for end in range(start, min(token_count, start + max_join)):
            parts.append(tokens[end])
            candidate = ", ".join(parts)
            if candidate in taxonomy_titles:
                span = end - start + 1
                edges[start].append((end + 1, span, candidate))

    best_from = [0] * (token_count + 1)
    for start in range(token_count - 1, -1, -1):
        best_from[start] = max(weight + best_from[end] for end, weight, _ in edges[start])

    optimal_edges = {start: [] for start in range(token_count)}
    for start in range(token_count):
        for end, weight, candidate in edges[start]:
            if weight + best_from[end] == best_from[start]:
                optimal_edges[start].append((end, weight, candidate))

    ways_prefix = [0] * (token_count + 1)
    ways_prefix[0] = 1
    for start in range(token_count):
        for end, _, _ in optimal_edges[start]:
            ways_prefix[end] += ways_prefix[start]

    ways_suffix = [0] * (token_count + 1)
    ways_suffix[token_count] = 1
    for start in range(token_count - 1, -1, -1):
        ways_suffix[start] = sum(ways_suffix[end] for end, _, _ in optimal_edges[start])

    total_optimal_paths = ways_suffix[0]
    guaranteed_segments = []
    covered_positions = set()

    for start in range(token_count):
        for end, weight, candidate in optimal_edges[start]:
            if weight == 0:
                continue
            if ways_prefix[start] * ways_suffix[end] == total_optimal_paths:
                guaranteed_segments.append((start, end, candidate))
                covered_positions.update(range(start, end))

    guaranteed_segments.sort(key=lambda item: (item[0], item[1]))
    unresolved_positions = [pos for pos in range(token_count) if pos not in covered_positions]
    return guaranteed_segments, unresolved_positions


mcf_path = "data/mcf_entrylevel.csv"
taxo_path = "data/skills_taxo.csv"

jobs_df = pd.read_csv(mcf_path, encoding="utf-8-sig")
taxo_df = pd.read_csv(taxo_path, encoding="utf-8-sig")

taxonomy_titles = {
    str(value).strip()
    for value in taxo_df["parent_skill_title"].dropna()
    if str(value).strip()
}

all_skills = []
remaining_mismatch_rows = []

for idx, row in jobs_df.iterrows():
    raw_text = str(row.get("extracted_skills", "")).strip()
    if not raw_text:
        continue

    row_skills = [part.strip() for part in raw_text.split("|") if part.strip()]
    all_skills.extend(row_skills)

    row_mismatches = [skill for skill in row_skills if skill not in taxonomy_titles]
    for skill in row_mismatches:
        remaining_mismatch_rows.append(
            {
                "row_number": idx + 2,
                "uuid": row.get("uuid", ""),
                "title": row.get("title", ""),
                "remaining_mismatch_skill": skill,
                "full_extracted_skills": raw_text,
            }
        )

unique_skills = sorted(set(all_skills))
remaining_mismatches = sorted(set(row["remaining_mismatch_skill"] for row in remaining_mismatch_rows))

remaining_mismatch_df = (
    pd.DataFrame(remaining_mismatch_rows)
    .sort_values(["remaining_mismatch_skill", "row_number"], ascending=[True, True])
    .reset_index(drop=True)
)

still_recombinable_rows = []
for idx, row in jobs_df.iterrows():
    raw_text = str(row.get("extracted_skills", "")).strip()
    if not raw_text:
        continue

    tokens = [part.strip() for part in raw_text.split("|") if part.strip()]
    guaranteed_segments, unresolved_positions = _solve_skill_token_sequence(
        tokens,
        taxonomy_titles,
        max_join=6,
    )

    has_recombined_segments = any((end - start) > 1 for start, end, _ in guaranteed_segments)
    if unresolved_positions and has_recombined_segments:
        still_recombinable_rows.append(
            {
                "row_number": idx + 2,
                "uuid": row.get("uuid", ""),
                "title": row.get("title", ""),
                "extracted_skills": raw_text,
                "unresolved_tokens": " | ".join(tokens[pos] for pos in unresolved_positions),
            }
        )

still_recombinable_df = pd.DataFrame(still_recombinable_rows)

print("Verification summary")
print(f"Total rows: {len(jobs_df)}")
print(f"Unique extracted skills after update: {len(unique_skills)}")
print(f"Unique skills matching taxonomy exactly: {len(unique_skills) - len(remaining_mismatches)}")
print(f"Unique skills still not matching taxonomy: {len(remaining_mismatches)}")
print(f"Rows that still look recombinable: {len(still_recombinable_df)}")

Verification summary
Total rows: 1587
Unique extracted skills after update: 1552
Unique skills matching taxonomy exactly: 1549
Unique skills still not matching taxonomy: 3
Rows that still look recombinable: 0

In [47]:
print("\nRemaining mismatched skills")
remaining_mismatch_df

Remaining mismatched skills

,row_number,uuid,title,remaining_mismatch_skill,full_extracted_skills
0,1016,aab49715cf3c6eb5dc75825962dfab27,Conference Producer / Conference Marketing Spe...,Conferences and Exhibitions (MICE) Content and...,"Events Planning and Management | Meetings, Inc..."
1,386,082f2fdd8c165579c89fa2dafc96a020,Robotics Technical Assistant,Conferences and Exhibitions (MICE) Equipment M...,Robotic and Automation System Maintenance | Me...
2,879,489f02ba79a0a11669e9b790b6b88f13,Administrative Assistant,Conferences and Exhibitions (MICE) Equipment M...,"Business Presentation Delivery | Meetings, Inc..."
3,753,30d38911187b8c345cd04c7b000062e1,ARCHITECTURAL ASSISTANT,nan,nan

In [49]:
for _, row in remaining_mismatch_df.iterrows():
    print(f"row_number: {row['row_number']}")
    print(f"remaining_mismatch_skill: {row['remaining_mismatch_skill']}")
    print(f"full_extracted_skills: {row['full_extracted_skills']}")
    print("-" * 120)

row_number: 1016
remaining_mismatch_skill: Conferences and Exhibitions (MICE) Content and Experience Development and Delivery
full_extracted_skills: Events Planning and Management | Meetings, Incentives, Conferences and Exhibitions (MICE) Equipment Management and Venue Management | Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Market Research | Excellence in Service | Infrastructure Support | Problem Management | Mass Communications Management | Business Presentation Delivery | Customer Challenges Management | Engagement Planning | Scheduling and Slot Coordination | Partnership Management | Content Writing and Editing | News Editing | Technical Presentation | Apply teamwork in the workplace | Project Integration | System and Work Process Improvement | Qualitative Research | Applications Development | Project Timeline | Dispute Resolution | Market Intelligence
------------------------------------------------------------------------------------------------------------------------
row_number: 386
remaining_mismatch_skill: Conferences and Exhibitions (MICE) Equipment Management and Venue Management
full_extracted_skills: Robotic and Automation System Maintenance | Meetings, Incentives, Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Robotic and Automation Technology Application | Maintenance and Repair | Engineering Support Management | Technical Sales Support | Technical Presentation | Automation Design | Equipment Maintenance and Housekeeping | Conferences and Exhibitions (MICE) Equipment Management and Venue Management | Electrical Engineering Management | Equipment and Inventory Management | Human-Robot Collaboration | Design for Safety | Automation Research and Implementation | Engineering Problem Solving | Quality Improvement and Safe Practices | Apply Workplace Safety and Health in Logistics and Transportation | Maintenance Scheduling | Visual Design and Communication Principles | Customer Service Excellence | Embedded Systems Programming | Electrical and Electronic Systems Maintenance | IT Strategy | Attractions Membership, Admission and Ticketing Management | Applications Development | Tour and Travel Services Product and Experience Development and Delivery | Power Plant Incident Investigation Management | Art Form Showcase | Documentation and Administration
------------------------------------------------------------------------------------------------------------------------
row_number: 879
remaining_mismatch_skill: Conferences and Exhibitions (MICE) Equipment Management and Venue Management
full_extracted_skills: Business Presentation Delivery | Meetings, Incentives, Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Conferences and Exhibitions (MICE) Equipment Management and Venue Management | Documentation and Administration | Workplace Optimisation | Green Facilities Management | Professional Standards | Infrastructure Support | Professional Ethics | Business Needs Analysis | Vision Leadership | Professional and Business Ethics | Public Areas Housekeeping Operations Management | Personal Effectiveness | Staff Communication and Engagement | Learning and Development Strategy | Project Coordination | Tourism Promotion | Group Work Assessment and Planning | Practice Supervision | Project Quality | Scheduling and Slot Coordination | Billing and Settlement Administration | Innovation | Customer Relationship Management Operations | Carbon Credit Project Development | Report Writing | Collaborative Practices with Stakeholders across Disciplines | Call Centre Management | Cost Management | Apply teamwork in the workplace | Project Scope
------------------------------------------------------------------------------------------------------------------------
row_number: 753
remaining_mismatch_skill: nan
full_extracted_skills: nan
------------------------------------------------------------------------------------------------------------------------

so actually the previous code have patched it up already, so now it just an incomplete duplicate, will remove

In [50]:
mcf_path = "data/mcf_entrylevel.csv"
df = pd.read_csv(mcf_path, encoding="utf-8-sig")

rows_to_clean = {
    386: "Conferences and Exhibitions (MICE) Equipment Management and Venue Management",
    879: "Conferences and Exhibitions (MICE) Equipment Management and Venue Management",
    1016: "Conferences and Exhibitions (MICE) Content and Experience Development and Delivery",
}

for row_number, skill_to_remove in rows_to_clean.items():
    idx = row_number - 2  # convert printed row_number back to dataframe index
    raw_text = str(df.at[idx, "extracted_skills"]).strip()
    skills = [part.strip() for part in raw_text.split("|") if part.strip()]

    if skill_to_remove not in skills:
        print(f"Row {row_number}: target skill not found, skipped")
        continue

    cleaned_skills = [skill for skill in skills if skill != skill_to_remove]
    df.at[idx, "extracted_skills"] = " | ".join(cleaned_skills)
    print(f"Row {row_number}: removed '{skill_to_remove}'")

print("\nUpdated rows:")
for row_number in rows_to_clean:
    idx = row_number - 2
    print(f"\nrow_number: {row_number}")
    print(f"title: {df.at[idx, 'title']}")
    print(f"extracted_skills: {df.at[idx, 'extracted_skills']}")

Row 386: removed 'Conferences and Exhibitions (MICE) Equipment Management and Venue Management'
Row 879: removed 'Conferences and Exhibitions (MICE) Equipment Management and Venue Management'
Row 1016: removed 'Conferences and Exhibitions (MICE) Content and Experience Development and Delivery'

Updated rows:

row_number: 386
title: Robotics Technical Assistant
extracted_skills: Robotic and Automation System Maintenance | Meetings, Incentives, Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Robotic and Automation Technology Application | Maintenance and Repair | Engineering Support Management | Technical Sales Support | Technical Presentation | Automation Design | Equipment Maintenance and Housekeeping | Electrical Engineering Management | Equipment and Inventory Management | Human-Robot Collaboration | Design for Safety | Automation Research and Implementation | Engineering Problem Solving | Quality Improvement and Safe Practices | Apply Workplace Safety and Health in Logistics and Transportation | Maintenance Scheduling | Visual Design and Communication Principles | Customer Service Excellence | Embedded Systems Programming | Electrical and Electronic Systems Maintenance | IT Strategy | Attractions Membership, Admission and Ticketing Management | Applications Development | Tour and Travel Services Product and Experience Development and Delivery | Power Plant Incident Investigation Management | Art Form Showcase | Documentation and Administration

row_number: 879
title: Administrative Assistant
extracted_skills: Business Presentation Delivery | Meetings, Incentives, Conferences and Exhibitions (MICE) Content and Experience Development and Delivery | Documentation and Administration | Workplace Optimisation | Green Facilities Management | Professional Standards | Infrastructure Support | Professional Ethics | Business Needs Analysis | Vision Leadership | Professional and Business Ethics | Public Areas Housekeeping Operations Management | Personal Effectiveness | Staff Communication and Engagement | Learning and Development Strategy | Project Coordination | Tourism Promotion | Group Work Assessment and Planning | Practice Supervision | Project Quality | Scheduling and Slot Coordination | Billing and Settlement Administration | Innovation | Customer Relationship Management Operations | Carbon Credit Project Development | Report Writing | Collaborative Practices with Stakeholders across Disciplines | Call Centre Management | Cost Management | Apply teamwork in the workplace | Project Scope

row_number: 1016
title: Conference Producer / Conference Marketing Specialist
extracted_skills: Events Planning and Management | Meetings, Incentives, Conferences and Exhibitions (MICE) Equipment Management and Venue Management | Market Research | Excellence in Service | Infrastructure Support | Problem Management | Mass Communications Management | Business Presentation Delivery | Customer Challenges Management | Engagement Planning | Scheduling and Slot Coordination | Partnership Management | Content Writing and Editing | News Editing | Technical Presentation | Apply teamwork in the workplace | Project Integration | System and Work Process Improvement | Qualitative Research | Applications Development | Project Timeline | Dispute Resolution | Market Intelligence

In [51]:
df.to_csv(mcf_path, index=False, encoding="utf-8-sig")